
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int cre_teb = 53;
  public static final int igua = 88;
  public static final int cre_tea = 52;
  public static final int parC = 78;
  public static final int setBo = 62;
  public static final int cre_img = 54;
  public static final int parA = 77;
  public static final int bord = 40;
  public static final int echo = 42;
  public static final int ima_c = 20;
  public static final int ima_a = 19;
  public static final int cli_bot = 67;
  public static final int hs_c = 68;
  public static final int hs_a = 41;
  public static final int lesigu = 83;
  public static final int fil_c = 26;
  public static final int div = 72;
  public static final int setAn = 59;
  public static final int fil_a = 25;
  public static final int setAl = 57;
  public static final int diff = 87;
  public static final int mas = 69;
  public static final int tru = 31;
  public static final int corC = 82;
  public static final int getT = 66;
  public static final int elsee = 44;
  public static final int corA = 81;
  public static final int getP = 56;
  public static final int colc_c = 28;
  public static final int cue_c = 9;
  public static final int getBo = 63;
  public static final int tit_c = 7;
  public static final int colc_a = 27;
  public static final int cue_a = 8;
  public static final int tit_a = 6;
  public static final int cie = 92;
  public static final int pyc = 76;
  public static final int getC = 51;
  public static final int getA = 49;
  public static final int igu = 73;
  public static final int or = 90;
  public static final int getAn = 60;
  public static final int anch = 37;
  public static final int getAl = 58;
  public static final int inser = 46;
  public static final int fals = 32;
  public static final int path = 35;
  public static final int esp_c = 11;
  public static final int alin = 34;
  public static final int esp_a = 10;
  public static final int setT = 65;
  public static final int and = 89;
  public static final int greigu = 84;
  public static final int setP = 55;
  public static final int texto = 98;
  public static final int men = 70;
  public static final int les = 85;
  public static final int ife = 43;
  public static final int cad = 95;
  public static final int repet = 45;
  public static final int EOF = 0;
  public static final int setC = 50;
  public static final int tab_c = 24;
  public static final int cre_tab = 61;
  public static final int umen = 99;
  public static final int setA = 48;
  public static final int tab_a = 23;
  public static final int cre_par = 47;
  public static final int gre = 86;
  public static final int alto = 36;
  public static final int error = 1;
  public static final int teb_c = 18;
  public static final int teb_a = 17;
  public static final int idvar = 96;
  public static final int text = 39;
  public static final int tea_c = 16;
  public static final int tea_a = 15;
  public static final int fond = 33;
  public static final int salt = 14;
  public static final int bot_c = 22;
  public static final int cre_bot = 64;
  public static final int cab_c = 5;
  public static final int bot_a = 21;
  public static final int por = 71;
  public static final int cab_a = 4;
  public static final int idobj = 97;
  public static final int com_c = 3;
  public static final int com_a = 2;
  public static final int coma = 74;
  public static final int par_c = 13;
  public static final int pun = 75;
  public static final int col_c = 30;
  public static final int not = 91;
  public static final int llavC = 80;
  public static final int par_a = 12;
  public static final int col_a = 29;
  public static final int llavA = 79;
  public static final int ide = 38;
  public static final int dec = 94;
  public static final int num = 93;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "com_a",
  "com_c",
  "cab_a",
  "cab_c",
  "tit_a",
  "tit_c",
  "cue_a",
  "cue_c",
  "esp_a",
  "esp_c",
  "par_a",
  "par_c",
  "salt",
  "tea_a",
  "tea_c",
  "teb_a",
  "teb_c",
  "ima_a",
  "ima_c",
  "bot_a",
  "bot_c",
  "tab_a",
  "tab_c",
  "fil_a",
  "fil_c",
  "colc_a",
  "colc_c",
  "col_a",
  "col_c",
  "tru",
  "fals",
  "fond",
  "alin",
  "path",
  "alto",
  "anch",
  "ide",
  "text",
  "bord",
  "hs_a",
  "echo",
  "ife",
  "elsee",
  "repet",
  "inser",
  "cre_par",
  "setA",
  "getA",
  "setC",
  "getC",
  "cre_tea",
  "cre_teb",
  "cre_img",
  "setP",
  "getP",
  "setAl",
  "getAl",
  "setAn",
  "getAn",
  "cre_tab",
  "setBo",
  "getBo",
  "cre_bot",
  "setT",
  "getT",
  "cli_bot",
  "hs_c",
  "mas",
  "men",
  "por",
  "div",
  "igu",
  "coma",
  "pun",
  "pyc",
  "parA",
  "parC",
  "llavA",
  "llavC",
  "corA",
  "corC",
  "lesigu",
  "greigu",
  "les",
  "gre",
  "diff",
  "igua",
  "and",
  "or",
  "not",
  "cie",
  "num",
  "dec",
  "cad",
  "idvar",
  "idobj",
  "texto",
  "umen"
  };
}

